package database

import (
	"path/filepath"
	"testing"

	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

// fixture is a minimal model used only to exercise the AutoMigrate /
// soft-delete behavior of the database layer. It is intentionally
// not part of the public API. It must NOT redeclare ID — the
// embedded BaseModel supplies the column.
type fixture struct {
	Name  string `gorm:"uniqueIndex"`
	Count int    `gorm:"default:0"`
	BaseModel
}

func openTestDB(t *testing.T) *gorm.DB {
	t.Helper()
	dir := t.TempDir()
	dsn := filepath.Join(dir, "test.db")
	db, err := gorm.Open(sqlite.Open(dsn), &gorm.Config{})
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	if err := db.AutoMigrate(&fixture{}); err != nil {
		t.Fatalf("migrate: %v", err)
	}
	t.Cleanup(func() {
		sqlDB, _ := db.DB()
		if sqlDB != nil {
			_ = sqlDB.Close()
		}
	})
	return db
}

func TestOpen_DefaultDriver(t *testing.T) {
	// GIVEN a sqlite DSN
	// WHEN Open is called without a driver
	// THEN the sqlite driver is chosen
	dir := t.TempDir()
	cfg := ConnectionConfig{Driver: "sqlite", DSN: filepath.Join(dir, "x.db")}

	db, err := Open(cfg)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	if db.Dialector.Name() != "sqlite" {
		t.Errorf("dialector = %q, want sqlite", db.Dialector.Name())
	}
}

func TestOpen_UnsupportedDriverFails(t *testing.T) {
	// GIVEN an unsupported driver name
	// WHEN Open is called
	// THEN an error is returned
	_, err := Open(ConnectionConfig{Driver: "oracle", DSN: "x"})
	if err == nil {
		t.Error("expected error for unsupported driver")
	}
}

func TestBaseModel_IDIsAutoGeneratedUUID(t *testing.T) {
	// GIVEN a fresh model inserted into the DB
	// WHEN its ID is read back
	// THEN it is a non-empty UUID string
	db := openTestDB(t)
	f := &fixture{Name: "alpha", Count: 1}
	if err := db.Create(f).Error; err != nil {
		t.Fatalf("create: %v", err)
	}
	if f.ID == "" {
		t.Error("ID was not set on insert")
	}
	if _, err := uuidFromString(f.ID); err != nil {
		t.Errorf("ID %q is not a UUID: %v", f.ID, err)
	}
}

func TestBaseModel_SoftDeleteHidesAndUnscopes(t *testing.T) {
	// GIVEN a fixture row that has been soft-deleted
	// WHEN queried normally
	// THEN the row is hidden
	// AND when queried with Unscoped, it is visible
	db := openTestDB(t)
	f := &fixture{Name: "beta", Count: 1}
	if err := db.Create(f).Error; err != nil {
		t.Fatalf("create: %v", err)
	}
	if err := db.Delete(f).Error; err != nil {
		t.Fatalf("soft delete: %v", err)
	}

	var got fixture
	if err := db.First(&got, "name = ?", "beta").Error; err == nil {
		t.Error("soft-deleted row should be hidden from default query")
	}
	if err := db.Unscoped().First(&got, "name = ?", "beta").Error; err != nil {
		t.Errorf("soft-deleted row should be visible to Unscoped: %v", err)
	}
}

func TestBaseModel_UniqueConstraintRejectsDuplicates(t *testing.T) {
	// GIVEN a row with name="dup"
	// WHEN a second row with name="dup" is inserted
	// THEN the database rejects it
	db := openTestDB(t)
	if err := db.Create(&fixture{Name: "dup", Count: 1}).Error; err != nil {
		t.Fatalf("first create: %v", err)
	}
	err := db.Create(&fixture{Name: "dup", Count: 2}).Error
	if err == nil {
		t.Error("expected unique-constraint violation")
	}
}

func TestBaseModel_TimestampsPopulated(t *testing.T) {
	// GIVEN a fresh row
	// WHEN read back
	// THEN CreatedAt and UpdatedAt are non-zero
	db := openTestDB(t)
	f := &fixture{Name: "ts"}
	if err := db.Create(f).Error; err != nil {
		t.Fatalf("create: %v", err)
	}
	if f.CreatedAt.IsZero() {
		t.Error("CreatedAt is zero")
	}
	if f.UpdatedAt.IsZero() {
		t.Error("UpdatedAt is zero")
	}
}
