{{ if .Values.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace | default "default" }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.encryptedData }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      name: {{ .Values.name }}
      namespace: {{ .Values.namespace | default "default" }}
{{ end }}
