{{ if and .Values.enabled .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "external-secrets.fullname" . }}
spec:
  refreshInterval: {{ .Values.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.target.name | default "devops-toolkit-secrets" }}
  data:
    {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
    {{- end }}
{{ end }}